import nbformat as nbf, os
os.makedirs('backend/brain/rebuild_notebooks', exist_ok=True)
nb = nbf.v4.new_notebook()
nb.cells.append(nbf.v4.new_markdown_cell("# Partner Demand Forecaster — EDA + XGBoost Quantile Rebuild\nAnalyst notes: load export EDA, inspect partner-country pairs, build q10/q50/q90 XGB regressors."))
nb.cells.append(nbf.v4.new_code_cell("import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import mean_absolute_error\nimport xgboost as xgb, joblib, json\ndf = pd.read_csv('backend/brain/data/final_csv/01_partner_discovery_india_as_exporter_eda.csv', nrows=50000)\nprint('Shape', df.shape)\nprint(df[['partner_name','hs6','trade_value_usd','year']].head())\n"))
nb.cells.append(nbf.v4.new_markdown_cell("## Missingness / target (demand proxy = trade_value_usd)"))
nb.cells.append(nbf.v4.new_code_cell("missing=df.isnull().mean().sort_values(ascending=False)\nprint(missing.head())\nprint('Year range', df['year'].min(), df['year'].max())\n"))
nb.cells.append(nbf.v4.new_markdown_cell("## Quantile regression — q50 baseline"))
nb.cells.append(nbf.v4.new_code_cell("num=['trade_value_usd','net_weight_kg'] if 'net_weight_kg' in df.columns else ['trade_value_usd']\nnum=[c for c in num if c in df.columns]\nX=df[['partner_name','hs6','year']+num].fillna(0)\n# encode categoricals quickly via factorize for rebuild demo\nX['partner_enc']=X['partner_name'].astype('category').cat.codes\nX['hs6_enc']=X['hs6'].astype('category').cat.codes\nX=X[['partner_enc','hs6_enc','year']+num]\ny=df['trade_value_usd'].fillna(0).values\nXtr,Xte,ytr,yte=train_test_split(X,y,test_size=0.2,random_state=42)\nclf=xgb.XGBRegressor(objective='reg:quantileerror',quantile_alpha=0.5,n_estimators=100,max_depth=5,learning_rate=0.05,n_jobs=-1,random_state=42)\nclf.fit(Xtr,ytr)\nprint('MAE', mean_absolute_error(yte,clf.predict(Xte)))\n"))
nb.cells.append(nbf.v4.new_markdown_cell("## Save rebuild artifacts"))
nb.cells.append(nbf.v4.new_code_cell("os.makedirs('backend/brain/models_rebuild/partner_discovery_xgb',exist_ok=True)\njoblib.dump(clf,'backend/brain/models_rebuild/partner_discovery_xgb/demand_q50.joblib')\nwith open('backend/brain/models_rebuild/partner_discovery_xgb/metadata.json','w') as f: json.dump({'type':'XGBRegressor_quantile','rebuild':'2026-08-26'},f)\nprint('Partner artifacts saved.')\n"))
nb.cells.append(nbf.v4.new_markdown_cell("Notes: full dataset 16MB. Notebook uses 50k sample for rebuild speed; production uses full `01_partner_discovery_india_as_exporter_eda.csv`. Artifacts saved to rebuild folder only."))
with open('backend/brain/rebuild_notebooks/03_partner_demand_forecaster.ipynb','w') as f: nbf.write(nb,f)
print('03 written')
