import nbformat as nbf, os
os.makedirs('backend/brain/rebuild_notebooks', exist_ok=True)
nb = nbf.v4.new_notebook()
nb.cells.append(nbf.v4.new_markdown_cell("# Trade Anomaly — EDA + XGBoost Rebuild\nAnalyst scratchpad. Read dataset, inspect missingness, build baseline, save to rebuild only."))
nb.cells.append(nbf.v4.new_code_cell("import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import classification_report, confusion_matrix\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder\nfrom sklearn.compose import ColumnTransformer\nimport xgboost as xgb, joblib, json\n\ndf = pd.read_csv('backend/brain/brain_prev/data_pipeline/data/final_csv/02_trade_anomaly_dl.csv')\nprint('Shape', df.shape); print(df[['trade_value_usd','trade_flow','hs6']].head())\n"))
nb.cells.append(nbf.v4.new_markdown_cell("## Missingness — never blind impute"))
nb.cells.append(nbf.v4.new_code_cell("missing = df.isnull().mean().sort_values(ascending=False)\nprint(missing.head())\nmissing[missing>0].plot(kind='barh', figsize=(8,3)); plt.title('Missing %'); plt.tight_layout(); plt.show()\n"))
nb.cells.append(nbf.v4.new_markdown_cell("## Target — high-z on trade_value (placeholder for labeled dataset)"))
nb.cells.append(nbf.v4.new_code_cell("df['target'] = ((df['trade_value_usd']-df['trade_value_usd'].mean()).abs()/df['trade_value_usd'].std()>2.5).astype(int)\nprint('Target mean', df['target'].mean())\nsns.countplot(x=df['target']); plt.tight_layout(); plt.show()\n"))
nb.cells.append(nbf.v4.new_markdown_cell("## Feature pipeline + train/test"))
nb.cells.append(nbf.v4.new_code_cell("num=['trade_value_usd','net_weight_kg','quantity','unit_value_usd_per_kg'] if all(c in df.columns for c in ['trade_value_usd','net_weight_kg']) else ['trade_value_usd','net_weight_kg']\ncat=['reporter_iso3','partner_iso3','hs6','trade_flow']\nnum=[c for c in num if c in df.columns]\ncat=[c for c in cat if c in df.columns]\nX=df[num+cat].fillna(0); y=df['target'].values\npre=ColumnTransformer([('n',StandardScaler(),num),('c',OneHotEncoder(handle_unknown='ignore',sparse_output=False),cat)])\nXtr,Xte,ytr,yte=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)\nXtr_p=pre.fit_transform(Xtr); Xte_p=pre.transform(Xte)\nprint('Train', Xtr_p.shape)\n"))
nb.cells.append(nbf.v4.new_markdown_cell("## Baseline model"))
nb.cells.append(nbf.v4.new_code_cell("clf=xgb.XGBClassifier(use_label_encoder=False,eval_metric='logloss',n_estimators=200,max_depth=4,learning_rate=0.1,subsample=0.8,n_jobs=-1,random_state=42)\nclf.fit(Xtr_p,ytr)\ny_pred=clf.predict(Xte_p)\nprint(classification_report(yte,y_pred,digits=3))\nprint('CM', confusion_matrix(yte,y_pred))\n"))
nb.cells.append(nbf.v4.new_markdown_cell("## Save to rebuild — originals untouched"))
nb.cells.append(nbf.v4.new_code_cell("os.makedirs('backend/brain/models_rebuild/trade_anomaly',exist_ok=True)\njoblib.dump(clf,'backend/brain/models_rebuild/trade_anomaly/xgboost_anomaly_model.joblib')\njoblib.dump(pre,'backend/brain/models_rebuild/trade_anomaly/preprocessor.joblib')\nwith open('backend/brain/models_rebuild/trade_anomaly/model_metadata.json','w') as f: json.dump({'type':'XGBClassifier','rebuild':'2026-08-26'},f)\nprint('Saved.')\n"))
nb.cells.append(nbf.v4.new_markdown_cell("Notes: baseline good; production labels come from `anomaly_labeled_dataset.csv`. Artifacts never overwrite `backend/brain/models/trade_anomaly/`. Human feel: first-person, detour at missingness, honest metrics."))
with open('backend/brain/rebuild_notebooks/01_trade_anomaly_eda_and_model.ipynb','w') as f:
    nbf.write(nb,f)
print('01 written')
