import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1440px",
      },
    },
    extend: {
      colors: {
        "secondary-fixed": "#d7e3ff",
        "surface-variant": "#323537",
        "error": "#ffb4ab",
        "background": "#101415",
        "secondary": "#aac7ff",
        "tertiary-fixed": "#e0e3e4",
        "on-tertiary-fixed-variant": "#434748",
        "surface-container-high": "#272a2c",
        "error-container": "#93000a",
        "tertiary-container": "#ced1d2",
        "surface-container-low": "#191c1e",
        "on-primary-fixed-variant": "#004f58",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#aac7ff",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#00458e",
        "primary": "#c3f5ff",
        "inverse-primary": "#006875",
        "on-tertiary": "#2d3132",
        "on-primary-fixed": "#001f24",
        "primary-fixed-dim": "#00daf3",
        "on-primary": "#00363d",
        "surface-bright": "#363a3b",
        "on-primary-container": "#00626e",
        "surface": "#101415",
        "primary-container": "#00e5ff",
        "outline-variant": "#3b494c",
        "on-secondary-fixed": "#001b3e",
        "on-tertiary-container": "#565a5b",
        "on-tertiary-fixed": "#181c1d",
        "surface-tint": "#00daf3",
        "primary-fixed": "#9cf0ff",
        "inverse-surface": "#e0e3e5",
        "on-surface": "#e0e3e5",
        "secondary-container": "#0066cc",
        "surface-dim": "#101415",
        "on-secondary": "#002f65",
        "tertiary": "#eaedee",
        "tertiary-fixed-dim": "#c4c7c8",
        "surface-container": "#1d2022",
        "on-background": "#e0e3e5",
        "surface-container-lowest": "#0b0f10",
        "surface-container-highest": "#323537",
        "on-secondary-container": "#dfe8ff",
        "inverse-on-surface": "#2d3133",
        "on-surface-variant": "#bac9cc",
        "outline": "#849396",
        // Additional backward-compatibility aliases
        border: "#849396",
        input: "#3b494c",
        ring: "#00daf3",
        foreground: "#e0e3e5",
        destructive: {
          DEFAULT: "#ffb4ab",
          foreground: "#690005",
        },
        muted: {
          DEFAULT: "#323537",
          foreground: "#bac9cc",
        },
        popover: {
          DEFAULT: "#191c1e",
          foreground: "#e0e3e5",
        },
        card: {
          DEFAULT: "#191c1e",
          foreground: "#e0e3e5",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        unit: "8px",
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Figtree", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Figtree", "sans-serif"],
        // Smooth, warm, non-sharp typography system
        sans: ["Figtree", "Outfit", "sans-serif"],
        display: ["Outfit", "Figtree", "sans-serif"],
        serif: ["Instrument Serif", "serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        scan: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100%)" },
        },
        fadeUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        scan: "scan 2s linear infinite",
        "fade-up": "fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
